### ISSUE TITLE
Apostrophe::toText() is incorrect

### ISSUE THREAD

**Issue by PowerGamer1** [jstewmc/rtf#2]
Current implementation of `Apostrophe::toText()` handles the hex character code represented by `\'xx` RTF control symbol as if it is an UTF-8 code which is completely wrong. In reality the character encoding of this code is determined by the RTF control words `\ansi`, `\pc`, `\pca`, `\mac` and `\ansicpgN`. So the correct conversion to text should utilize PHP `iconv` function.

Example of determining RTF encoding for use in `iconv`:

``` PHP
    function parseEncoding(\Jstewmc\Rtf\Element\Group $root)
    {
        if($root->getControlWords('pc') != [])
            $encoding = 'IBM437';
        else if($root->getControlWords('pca') != [])
            $encoding = 'IMB850';
        else if($root->getControlWords('mac') != [])
            $encoding = 'macintosh';
        else
        {
            $ansicpg = $root->getControlWords('ansicpg');
            if($ansicpg != [])
            {
                switch($ansicpg[0])
                {
                case '708':
                    $encoding = 'ISO-8859-6';
                    break;
                    // TODO: the rest of RTF code pages
                default:
                    $encoding = 'windows-' . $ansicpg[0]->getParameter();
                }
            }
            else
                $encoding = 'windows-1252';
        }

        $this->encoding = $encoding;
    }
```

Example of correctly converting `\'xx` control words to text:

``` PHP
function toText(\Jstewmc\Rtf\Element\Control\Symbol\Apostrophe $symbol, $encoding)
{
    return iconv($encoding, 'UTF-8', hex2bin($symbol->getParameter()))
}
```

**Comment by jstewmc** [comment]
Hmm, well this is definitely not good news haha. 

When I wrote the library, I knew I would only be working with ASCII characters (and converting them to UTF-8). So, I purposely skimmed over encoding, and I didn't give it the treatment it deserved.

However, this is one of my most popular libraries. I may not need it, but for the good of the community and because I may or may not be slightly OCD, I'll circle back, dive into it, and fix this issue. Luckily, you've done most of the work for me! 

Thank you for the well-documented issue and for the great code sample. Things are pretty busy these days, but I'll try to get to it in the next few weeks.
